services:
  kengash_web:
    build:
        context: ./app
        dockerfile: Dockerfile.prod
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    expose:
      - 8000
    env_file:
      - ./.env.prod
    restart: always
    volumes:
      - static_volume:/app/staticfiles
      - ./media-files:/app/media-files
    depends_on:
      - kengash_db
  kengash_db:
    image: postgres:16
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.db
    ports:
      - "5430:5432"

  nginx:
    build: ./nginx
    ports:
      - "2014:80"
    depends_on:
      - kengash_web
    volumes:
      - static_volume:/app/staticfiles
      - ./media-files:/app/media-files
    restart: always

volumes:
  postgres_data:
  static_volume:
