FROM python:3.12-slim

WORKDIR /app

RUN addgroup --system app && adduser --system --group kengash

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

RUN apt-get update && apt-get install -y netcat-openbsd

COPY requirements.txt .

RUN pip install  -r requirements.txt

COPY entrypoint.dev.sh .
RUN sed -i 's/\r$//g' /app/entrypoint.dev.sh
RUN chmod +x /app/entrypoint.dev.sh

RUN mkdir staticfiles

COPY . .

RUN chown -R kengash:app /app
USER kengash
ENTRYPOINT ["sh", "/app/entrypoint.dev.sh"]
CMD ["python", "bot.py"]