FROM python:3.12-slim

WORKDIR /app

RUN addgroup --system app && adduser --system --group kengash

ENV PYTHONUNBUFFERED 1

RUN apt-get update && apt-get install -y netcat-openbsd

COPY requirements.txt .

RUN pip install -r requirements.txt

COPY entrypoint.prod.sh .
RUN sed -i 's/\r$//g' /app/entrypoint.prod.sh
RUN chmod +x /app/entrypoint.prod.sh

RUN mkdir staticfiles

COPY . .

RUN chown -R kengash:app /app

USER kengash
ENTRYPOINT ["sh", "/app/entrypoint.prod.sh"]
