# Generated by Django 5.1.4 on 2025-02-19 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0002_selectedemployee_vote'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='session_id',
            field=models.UUIDField(null=True),
        ),
        migrations.AlterField(
            model_name='selectedemployee',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selected_employee', to='teachers.employee'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='teachers.selectedemployee'),
        ),
    ]
