# Generated by Django 5.1.4 on 2024-12-06 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0002_allowedteachers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('birth_date', models.CharField(max_length=200)),
                ('shifr', models.CharField(max_length=200)),
                ('position', models.CharField(max_length=200)),
                ('year', models.CharField(blank=True, max_length=200, null=True)),
                ('equal', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('dotsent', 'dotsent'), ('professor', 'professor')], default='dotsent', max_length=100)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_teachers', to='teachers.employee')),
            ],
        ),
    ]
