# Generated by Django 5.1.4 on 2025-02-19 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0003_vote_session_id_alter_selectedemployee_employee_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='ip_address',
        ),
    ]
