# Generated by Django 5.1.4 on 2024-12-06 13:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0003_candidates'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidatesVotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote', models.CharField(choices=[('yes', 1), ('no', 0)], max_length=10, null=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_teacher', to='teachers.candidates')),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voter_teacher', to='teachers.allowedteachers')),
            ],
        ),
    ]
