# Generated by Django 5.1.4 on 2025-02-23 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0004_remove_vote_ip_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='selectedemployee',
            name='which_position',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='selectedemployee',
            name='type',
            field=models.CharField(choices=[('professor', 'Professor'), ('dotsent', 'Dotsent')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='vote',
            name='vote',
            field=models.CharField(choices=[('rozi', 'Roziman'), ('qarshi', 'Qarshiman'), ('betaraf', 'Betaraf')], max_length=20),
        ),
    ]
