# Generated by Django 5.1.4 on 2025-02-23 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0005_selectedemployee_which_position_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='selectedemployee',
            name='created_at',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='selectedemployee',
            name='type',
            field=models.CharField(choices=[('professor', 'Professor'), ('dotsent', 'Dotsent'), ('mudir', 'Mudir'), ('katta_oqituvchi', "Katta O'qituvchi"), ('oqituvchi_stajyor', "O'qituvchi-stajyor"), ("o'qituvchi", "O'qituvchi")], max_length=20, null=True),
        ),
    ]
