# Generated by Django 5.1.4 on 2025-02-23 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0006_selectedemployee_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selectedemployee',
            name='created_at',
            field=models.DateTimeField(null=True),
        ),
    ]
