# Generated by Django 5.1.4 on 2025-02-24 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0008_votingtimer'),
    ]

    operations = [
        migrations.AddField(
            model_name='selectedemployee',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='selectedemployee',
            name='voted',
            field=models.BooleanField(default=False),
        ),
    ]
