# Generated by Django 5.1.4 on 2025-02-25 06:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0010_selectedemployee_is_running_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='selectedemployee',
            name='is_running',
        ),
        migrations.RemoveField(
            model_name='selectedemployee',
            name='timer_seconds',
        ),
        migrations.AddField(
            model_name='selectedemployee',
            name='linked_employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_to', to='teachers.selectedemployee'),
        ),
    ]
